name: web_socket
description: Websocket handler for all platforms

version: 0.0.1-dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  json_serializable: ^6.0.0
  lints: ^2.0.0
  build_runner: ^2.0.3